import java.util.Scanner;

public class Main {

public static void main(String[] args) {

Scanner input = new Scanner(System.in);

System.out.print("Enter year: ");

int year = input.nextInt();

System.out.print("Enter month: ");

int month = input.nextInt();

System.out.print("Enter day of month: ");

int dayOfMonth = input.nextInt();

int daysInMonth = 31;

if (month == 4 || month == 6 || month == 9 || month == 11) {

daysInMonth = 30;

} else if (month == 2) {

if ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0) {

daysInMonth = 29;

} else {

daysInMonth = 28;

}

}

int dayOfWeek = (dayOfMonth + 2 * month + 3 * (month + 1) / 5 + year + year / 4 - year / 100 + year / 400) % 7;

System.out.println(" ");

System.out.println(" Sun Mon Tue Wed Thu Fri Sat");

for (int i = 0; i < dayOfWeek; i++) {

System.out.print("    ");

}

for (int i = 1; i <= daysInMonth; i++) {

System.out.printf("%4d", i);

if ((i + dayOfWeek) % 7 == 0) {

System.out.println();

}

}

System.out.println();

}

}
